
package Telas;

import Dao.UsuarioHospDao;
import Model.UsuarioHospedagem;
import javax.swing.JOptionPane;



/**
 *
 * @author maury
 */
public class TelaCadastroUsu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroUsu.class.getName());
    
 public UsuarioHospDao dao = new UsuarioHospDao(); //CRIANDO OBJETO DAO 
 
    public TelaCadastroUsu() {
        initComponents();} // CONSTRUTOR DA TELA 
        
    
  /*funçoes*/
     private void salvar(){
     
     UsuarioHospedagem  c = new UsuarioHospedagem ();// CRIANDO UM OBJETO VAZIO 
      
      c.setNome(NomeFun.getText());
      c.setLogin(Login.getText());
     c.setSenha(new String(Senha.getPassword()));
     c.setTipo(Tipo.getSelectedItem().toString());
     
      
      /*compo de validaçao, para que nao ocorra o cadastro de canpos vazios*/
      if(NomeFun.getText().isEmpty()||
           Login.getText().isEmpty()||
           Senha.getPassword().length == 0) {
           JOptionPane.showMessageDialog(null,"É obrigatorio preencher todos os campos");
            return;
        }
      
      boolean salvou = dao.salvar(c);
      if (salvou) {
    JOptionPane.showMessageDialog(this, "Cadastrado com sucesso");
    limpar();
} else {
    JOptionPane.showMessageDialog(this, "Erro ao salvar no banco");
}
     }
     
     private void limpar(){
     NomeFun.setText("");
     Login.setText("");
     Senha.setText("");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeFun = new javax.swing.JTextField();
        Tipo = new javax.swing.JComboBox<>();
        Login = new javax.swing.JTextField();
        Senha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        ButonCadastrar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ButonInicio1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomeFun.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        NomeFun.setBorder(null);
        NomeFun.setDisabledTextColor(new java.awt.Color(32, 32, 32));
        NomeFun.addActionListener(this::NomeFunActionPerformed);
        getContentPane().add(NomeFun, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 240, 27));

        Tipo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Recepcionista", " " }));
        Tipo.setBorder(null);
        Tipo.addActionListener(this::TipoActionPerformed);
        getContentPane().add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 135, -1, 20));

        Login.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Login.setBorder(null);
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 177, 250, 26));

        Senha.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        Senha.setBorder(null);
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 223, 250, 26));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Senha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        ButonCadastrar1.setBackground(new java.awt.Color(106, 141, 243));
        ButonCadastrar1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        ButonCadastrar1.setText("Cadastrar");
        ButonCadastrar1.setBorder(null);
        ButonCadastrar1.addActionListener(this::ButonCadastrar1ActionPerformed);
        getContentPane().add(ButonCadastrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 314, 130, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Crago:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Logim:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel10.setText("Cadastro");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        ButonInicio1.setBackground(new java.awt.Color(106, 141, 243));
        ButonInicio1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        ButonInicio1.setText("login");
        ButonInicio1.setBorder(null);
        ButonInicio1.addActionListener(this::ButonInicio1ActionPerformed);
        getContentPane().add(ButonInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 380, 65, 27));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Nome:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\maury\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoIntegradorUC15\\src\\main\\java\\Telas\\IMGCadatroUsu.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButonCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonCadastrar1ActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_ButonCadastrar1ActionPerformed

    private void NomeFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFunActionPerformed

    private void ButonInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonInicio1ActionPerformed
        // TODO add your handling code here:
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
    }//GEN-LAST:event_ButonInicio1ActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroUsu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonCadastrar1;
    private javax.swing.JButton ButonInicio1;
    private javax.swing.JTextField Login;
    private javax.swing.JTextField NomeFun;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
