/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Dao.UsuarioHospDao;
import Model.UsuarioHospedagem;
import javax.swing.JOptionPane;

/**
 *
 * @author maury
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

   
    public TelaLogin() {
        initComponents();
        
    }
    
    private void entrar (){
        String login = TextLogin.getText();
        String senha = new String(Password.getPassword()); // CONVERTENDO CHAR PARA STRING

        UsuarioHospDao dao = new UsuarioHospDao(); // CRIANDO DAO RESPONSAVAL PARA ACESAR DADOS
        UsuarioHospedagem usuario = dao.autenticar(login, senha); // ENVIA LOGIN E SENHA AO DAO

        if (usuario != null) // VALIDAÇAO 
        {
            JOptionPane.showMessageDialog(this,
                    "Bem-vindo " + usuario.getNome() +
                    ", sua permissão é: " + usuario.getTipo());

            Principal tela = new Principal(usuario);
            tela.setVisible(true);

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Login ou senha inválidos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextLogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextLogin.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        TextLogin.setBorder(null);
        TextLogin.addActionListener(this::TextLoginActionPerformed);
        getContentPane().add(TextLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 129, 300, 30));

        jButton1.setBackground(new java.awt.Color(106, 141, 243));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jButton1.setText("ENTRAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 305, 90, 30));

        jButton2.setBackground(new java.awt.Color(106, 141, 243));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton2.setText("Efetuar cadastro");
        jButton2.setBorder(null);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, 20));

        jLabel2.setFont(new java.awt.Font("Nirmala Text Semilight", 0, 36)); // NOI18N
        jLabel2.setText("login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Login:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        Password.setBorder(null);
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 207, 300, 29));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\maury\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoIntegradorUC15\\src\\main\\java\\Telas\\IMGTelaLogin.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        entrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       TelaCadastroUsu cadastro = new  TelaCadastroUsu();
        cadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLoginActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField TextLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
